### PR TITLE
Fix Last Pin Error

### LINKED ISSUE #81: Last Pin Error
When an incident channel has no pinned messages, the reminder searches for the last pinned message and not find it, it logs a `Last Pin error` and does not ask for the incident status.

```
jsonPayload: {
  app_name: "hellper"   
  channelID: "C015Q8L61A8"   
  error: "Lista está vazia"   
  level: "error"   
  log_type: "stdout"   
  message: "command/reminder.requestStatus LastPin error"   
  pod_name: "hellper-7f4cc474d7-89pvh"   
  raw: "{"level":"error","time":"2020-06-24T14:34:03.990Z","message":"command/reminder.requestStatus LastPin error","channelID":"C015Q8L61A8","error":"Lista está vazia","stack":"hellper/internal/log/zap.(*zapLoggerDelegate).Check\n\t/app/internal/log/zap/zap.go:32\nhellper/internal/log/zap.logger.log\n\t/app/internal/log/zap/zap.go:79\nhellper/internal/log/zap.logger.Error\n\t/app/internal/log/zap/zap.go:98\nhellper/internal/commands.requestStatus.func1\n\t/app/internal/commands/reminder.go:66\nhellper/internal/job.NewTrackable.func1\n\t/app/internal/job/job.go:26"}
```

### Cleanup

**What should be cleaned up or changed**:
We should not break the execution of the reminder with this error, we should keep asking for a status message.

**Provide any links for context**:

### PR DESCRIPTION
**Pull request by GLOFonseca**
### Description
Fix #81 

### How to test?
-Open an incident
-Remove pin from Hellper messages, leaving the channel with no message pinned

### Expected behavior
Hellper should ask for a status update

### CODE REVIEW

File: internal/bot/data_test.go [hunk 1]
```diff
@@ -1,35 +1,112 @@
...
+	item      slack.Item
+	itemList  []slack.Item
+
+	mockClient    bot.Client
+	listPinsError error
+}
+
+//1. Item, erro nil
+//2. n/a, error
+//3. vazio, erro nil
```
Comment (tiagoemsi) [inline internal/bot/data_test.go:28]: Are these comments necessary?

Comment (GLOFonseca) [reply internal/bot/data_test.go]: removed

**Comment by GLOFonseca** [comment]
@tiagoemsi fixed!
